[tool.poetry]
name = "omega"
version = "0.6.0"
description = "高速分布式证券数据服务器"
authors = ["jieyu <code@jieyu.ai>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
apscheduler = "^3.6.3"
arrow = "^0.15"
cfg4py = "^0"
aioredis = "^1.3.1"
hiredis = "^1.0.1"
numpy = "^1.18.1"
numba = "^0.49.1"
aiohttp = "^3.6.2"
pytz = "^2019.3"
xxhash = "^1.4.3"
zillionare-omicron = "^0"
aiocache = "^0.11.1"
sanic = "^20.3.0"
psutil = "^5.7.0"
termcolor = "^1.1.0"
gino = "^1.0.1"
asyncpg = "^0.21.0"
"ruamel.yaml" = "^0.16.0"
sh = "^1.14.1"
pyemit = "^0.4.5"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
tox = "^3.14.0"
coverage = "^4.5.4"
Sphinx = "^3.3.1"
black = "^20.8b1"
pre-commit = "^2.8.2"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
doc8 = "^0.8.1"
recommonmark = "^0.6.0"
jqdatasdk = "^1.8.3"
"zillionare-omicron" = {path = "/c/workspace/omicron"}
"zillionare-omega-adaptors-jq" = {path = "/c/workspace/omega_jqadaptor"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
omega = 'omega.cli:main'

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tests/.*/setup.py
)/
'''

[tool.isort]
# black compatible settings, see https://github.com/psf/black/blob/master/docs/compatible_configs
line_length = 88
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
multi_line_output = 3
use_parentheses = true
not_skip = "__init__.py"
skip_glob = ["*/setup.py"]
filter_files = true